# Generated by Django 5.0.1 on 2024-03-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastesPost',
            fields=[
                ('new_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.new')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.new', models.Model),
        ),
    ]
